services:
  web:
    container_name: my_cv
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
    command: yarn dev

volumes:
  nodemodules:
