export const expeData: expeEduData[] = [
  {
    id: 1,
    title: "Fullstack developer – Internship",
    fromDate: "2024",
    toDate: "2024",
    company: "Luday",
    location: "Remote",
  },
  {
    id: 2,
    title: "IT consultant – Founder",
    fromDate: "2023",
    toDate: "2023",
    company: "Södertälje Techhouse",
    location: "Södertälje, Sweden",
  },
  {
    id: 3,
    title: "Dataadmin - Consultant",
    fromDate: "2022",
    toDate: "2022",
    company: "Academic Work",
    location: "Remote",
  },
  {
    id: 4,
    title: "System Developer",
    fromDate: "2022",
    toDate: "2022",
    company: "Rektron",
    location: "Solna, Sweden",
  },
  {
    id: 5,
    title: "Javascript Developer",
    fromDate: "2021",
    toDate: "2021",
    company: "Soltia",
    location: "Tumba and Älvsjö, Sweden",
  },
  {
    id: 6,
    title: "Web Developer - Consultant",
    fromDate: "2020",
    toDate: "2020",
    company: "Kringelstan Webagency",
    location: "Södertälje, Sweden",
  },
  {
    id: 7,
    title: "Web Developer - Internship",
    fromDate: "2020",
    toDate: "2020",
    company: "Kringelstan Webagency",
    location: "Södertälje, Sweden",
  },
  {
    id: 8,
    title: "Web Development Teacher",
    fromDate: "2020",
    toDate: "2020",
    company: "Wendela Hebbegymnasiet",
    location: "Södertälje, Sweden",
  },
];

