import { GithubURLBase } from "./text-consts";

export const projectData: projectData[] = [
  {
    id: 1,
    title: "PixabayFinder",
    desc: "🖼️ An app to fetch images and videos from Pixabay.",
    URL: "https://pixabay-finder.vercel.app",
    GitURL: `${GithubURLBase}/PixabayFinder`,
    assetPath: "/Pixabayfinder.png",
  },
  {
    id: 2,
    title: "Intranat",
    desc: "🧑‍💼A dashboard application that helps staff communicate with their managers.",
    URL: "https://intranet.gssonsel.se.185-133-206-116.bb.kringelstan.se",
    GitURL: `${GithubURLBase}/Intranat`,
    assetPath: "/Intranat.png",
  },
  {
    id: 3,
    title: "Datahjälp",
    desc: "💻 Datahjälp is a company that informs customers about the company's prices and contact details for these companies. Datahjälp helps customers fix their computers.",
    URL: "https://fadihanna123.github.io/DatahjalpProjekt",
    GitURL: `${GithubURLBase}/DatahjalpProjekt`,
    assetPath: "/Datahjalp.png",
  },
  {
    id: 4,
    title: "Old My CV",
    desc: "🏢 A website to show my CV in webapplication.",
    URL: undefined,
    GitURL: `${GithubURLBase}/CV_React`,
    assetPath: "/CV_React.png",
  },
  {
    id: 5,
    title: "Din Restaurang",
    desc: "🍔 A restaurantapplication and adminpanel as shows and manages 5 food types.",
    URL: undefined,
    GitURL: `${GithubURLBase}/Din_Restaurang`,
    assetPath: "/Dinrestaurang.png",
  },
  {
    id: 6,
    title: "Chat Me",
    desc: "💬 A chatapplication to chat other people in the public chat. All messages will be shown in the chatroom.",
    URL: undefined,
    GitURL: `${GithubURLBase}/chatMe`,
    assetPath: "/ChatMe.png",
  },
  {
    id: 7,
    title: "Camera Website",
    desc: "A full-stack web application for login and register to manage and displaying videos as be taken of the camera.",
    URL: undefined,
    GitURL: `${GithubURLBase}/CameraWebsite`,
    assetPath: "/CameraWebsite.png",
  },
  {
    id: 8,
    title: "Billigast & Begagnade",
    desc: "A modern e-commerce website project built with HTML, CSS, TypeScript, and JavaScript.",
    URL: undefined,
    GitURL: `${GithubURLBase}/E-handelprojekt`,
    assetPath: "/E-handelproject.png",
  },
  {
    id: 9,
    title: "Chat App 2",
    desc: "A modern real-time chat application built with a React frontend and Node.js backend.",
    URL: undefined,
    GitURL: `${GithubURLBase}/chatapp`,
    assetPath: "/Chatapp2.png",
  },
  {
    id: 10,
    title: "Fadi Streams",
    desc: "A simple web-based video meeting app built with Agora RTC SDK and TypeScript.",
    URL: "https://fadistreams.vercel.app",
    GitURL: undefined,
    assetPath: "/FadiStreams.png",
  },
  {
    id: 11,
    title: "Movies Finder",
    desc: "A movie library app to search movies and learn know about it.",
    URL: "https://movies-finder-wine.vercel.app",
    GitURL: undefined,
    assetPath: "/moviesFinder.png",
  },
];
